<a href="https://colab.research.google.com/github/Sandip890/DWM/blob/main/Association_Apriori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd
import apyori
from apyori import apriori
from mlxtend.frequent_patterns import apriori, association_rules

In [15]:
data = pd.read_excel('/apriori.xlsx')

In [21]:
data

   1  1.1  0  1.2  0.1  1.3
0  1    1  1    1    1    0
1  1    1  1    0    1    0
2  1    1  1    0    1    0
3  1    1  0    1    0    0

In [22]:
frq_items = apriori(data, min_support = 0.6, use_colnames = True)
rules = association_rules(frq_items, metric = "confidence", min_threshold = 0.80) 
print(rules)

      antecedents    consequents  antecedent support  consequent support  \
0             (1)          (1.1)                1.00                1.00
1           (1.1)            (1)                1.00                1.00
2             (0)            (1)                0.75                1.00
3           (0.1)            (1)                0.75                1.00
4             (0)          (1.1)                0.75                1.00
5           (0.1)          (1.1)                0.75                1.00
6             (0)          (0.1)                0.75                0.75
7           (0.1)            (0)                0.75                0.75
8          (0, 1)          (1.1)                0.75                1.00
9        (0, 1.1)            (1)                0.75                1.00
10            (0)       (1, 1.1)                0.75                1.00
11       (1, 0.1)          (1.1)                0.75                1.00
12     (0.1, 1.1)            (1)                0.75                1.00
13          (0.1)       (1, 1.1)                0.75                1.00
14         (0, 1)          (0.1)                0.75                0.75
15       (0, 0.1)            (1)                0.75                1.00
16       (1, 0.1)            (0)                0.75                0.75
17            (0)       (1, 0.1)                0.75                0.75
18          (0.1)         (0, 1)                0.75                0.75
19       (0, 0.1)          (1.1)                0.75                1.00
20       (0, 1.1)          (0.1)                0.75                0.75
21     (0.1, 1.1)            (0)                0.75                0.75
22            (0)     (0.1, 1.1)                0.75                0.75
23          (0.1)       (0, 1.1)                0.75                0.75
24    (0, 1, 0.1)          (1.1)                0.75                1.00
25    (0, 1, 1.1)          (0.1)                0.75                0.75
26  (0, 0.1, 1.1)            (1)                0.75                1.00
27  (1, 0.1, 1.1)            (0)                0.75                0.75
28         (0, 1)     (0.1, 1.1)                0.75                0.75
29       (0, 0.1)       (1, 1.1)                0.75                1.00
30       (0, 1.1)       (1, 0.1)                0.75                0.75
31       (1, 0.1)       (0, 1.1)                0.75                0.75
32     (0.1, 1.1)         (0, 1)                0.75                0.75
33            (0)  (1, 0.1, 1.1)                0.75                0.75
34          (0.1)    (0, 1, 1.1)                0.75                0.75

    support  confidence      lift  leverage  conviction
0      1.00         1.0  1.000000    0.0000         inf
1      1.00         1.0  1.000000    0.0000         inf
2      0.75         1.0  1.000000    0.0000         inf
3      0.75         1.0  1.000000    0.0000         inf
4      0.75         1.0  1.000000    0.0000         inf
5      0.75         1.0  1.000000    0.0000         inf
6      0.75         1.0  1.333333    0.1875         inf
7      0.75         1.0  1.333333    0.1875         inf
8      0.75         1.0  1.000000    0.0000         inf
9      0.75         1.0  1.000000    0.0000         inf
10     0.75         1.0  1.000000    0.0000         inf
11     0.75         1.0  1.000000    0.0000         inf
12     0.75         1.0  1.000000    0.0000         inf
13     0.75         1.0  1.000000    0.0000         inf
14     0.75         1.0  1.333333    0.1875         inf
15     0.75         1.0  1.000000    0.0000         inf
16     0.75         1.0  1.333333    0.1875         inf
17     0.75         1.0  1.333333    0.1875         inf
18     0.75         1.0  1.333333    0.1875         inf
19     0.75         1.0  1.000000    0.0000         inf
20     0.75         1.0  1.333333    0.1875         inf
21     0.75         1.0  1.333333    0.1875         inf
22     0.75         1.0  1.333333    0.1875         inf
23     0.75         1.0  1.333333    0.1875         inf
24     0.75         1.0  1.000000    0.0000         inf
25     0.75         1.0  1.333333    0.1875         inf
26     0.75         1.0  1.000000    0.0000         inf
27     0.75         1.0  1.333333    0.1875         inf
28     0.75         1.0  1.333333    0.1875         inf
29     0.75         1.0  1.000000    0.0000         inf
30     0.75         1.0  1.333333    0.1875         inf
31     0.75         1.0  1.333333    0.1875         inf
32     0.75         1.0  1.333333    0.1875         inf
33     0.75         1.0  1.333333    0.1875         inf
34     0.75         1.0  1.333333    0.1875         inf